# Generated by Django 5.0.3 on 2024-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('ISBN', models.CharField(blank=True, max_length=14, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=40)),
                ('numbers', models.IntegerField()),
            ],
        ),
    ]
