# Generated by Django 5.0.3 on 2024-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_borrow_review_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='Book/media'),
        ),
    ]
